apiVersion: v1
kind: Service
metadata:
  name: petclinic-mysql
  labels:
    app: petclinic
spec:
  ports:
    - port: 3306
  selector:
    app: petclinic
    tier: mysql
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  labels:
    app: petclinic
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic-mysql
  labels:
    app: petclinic
spec:
  selector:
    matchLabels:
      app: petclinic
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: petclinic
        tier: mysql
    spec:
      containers:
      - image: mysql:latest
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secrets
              key: password

        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: secrets
              key: user

        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secrets
              key: password
              
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: secrets
              key: database
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
