apiVersion: v1
kind: Service
metadata:
  name: petclinic
  labels:
    app: petclinic
spec:
  selector:
    app: petclinic
  ports:
    - port: 8080
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic
  labels:
    app: petclinic
spec:
  selector:
    matchLabels:
      app: petclinic
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: petclinic
    spec:
      containers:
      - image: m1r3x/demo4:petclinic
        name: petclinic
        env:
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: secrets
              key: user

        - name: MYSQL_PASS
          valueFrom:
            secretKeyRef:
              name: secrets
              key: password

        - name: DB
          valueFrom:
            secretKeyRef:
              name: secrets
              key: database

        - name: MYSQL_URL
          value: jdbc:mysql://petclinic-mysql.default.svc.cluster.local:3306/$(DB)

        - name: SPRING_PROFILES_ACTIVE
          value: mysql

        ports:
        - containerPort: 8080
          name: petclinic

        livenessProbe:
          httpGet:
            path: /actuator/health
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
